services:
  sc-downloader:
    build: .
    container_name: sc-downloader
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/logs
    environment:
      - TZ=Australia/Brisbane
